project:
  name: Niamoto Project
  version: 1.0.0
  created_at: '2025-10-13T15:46:28.606939'
  niamoto_version: 0.7.2
database:
  path: db/niamoto.db
logs:
  path: logs
exports:
  web: exports/web
  api: exports/api
plugins:
  path: plugins
templates:
  path: templates
